export const InfoOne = {
    id: "about",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Premium Bank",
    headLine: "Unlimited Transactions with zero fees",
    description: "Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.",
    buttonLabel: "Get started",
    imgStart: false,
    img: require("../../img/svg-1.svg").default,
    alt: "Car",
    dark: true,
    primary: true,
    darkText: false,
};

export const InfoTwo = {
    id: "discover",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Unlimited Access",
    headLine: "Login to your account at any time",
    description: "We have you covered no matter where you are located. All you need is an internet connection and phone or computer.",
    buttonLabel: "Learn More",
    imgStart: true,
    img: require("../../img/svg-2.svg").default,
    alt: "Wallet",
    dark: false,
    primary: false,
    darkText: true,
};

export const InfoThree = {
    id: "signup",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Join our Team",
    headLine: "Creating an account is extremely easy",
    description: "Get everything set up and ready in under 10 minutes. All you need to do is add your information and you're ready to go.",
    buttonLabel: "Start Now",
    imgStart: false,
    img: require("../../img/svg-5.svg").default,
    alt: "Chart",
    dark: false,
    primary: false,
    darkText: true,
};
